version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  job_one:
    docker:
      - image: node:16
    steps:
      - run:
          name: Install npm dependencies
          command: echo npm install
      - run:
          name: Run Unit Tests
          command: echo npm test
  job_two:
    docker:
      - image: golang:latest
    steps:
      - run:
          name: Run Go Tests
          command: |
            echo go test
      - run:
          name: Run Go Build
          command: |
            echo go build
  orb_test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
workflows:
  test:
    jobs:
      - job_one
      - job_two
      - orb_test
  test_two:
    jobs:
      - job_two
