version: 2.1

jobs:
  job_one:
    docker:
      - image: node:16
    steps:
      - run:
          name: Install npm dependencies
          command: |
            echo npm install
      - run:
          name: Run Unit Tests
          command: |
            echo npm test
  job_two:
    docker:
      - image: golang:latest
    steps:
      - run:
          name: Run Go Tests
          command: |
            echo go test
      - run:
          name: Run Go Build
          command: |
            echo go build
workflows:
  build_test:
    jobs:
      - job_one
      - job_two
